{
 "title": "Pizza Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Logging",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(http_requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(delete_requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Delete"
    },
    {
     "expr": "rate(get_requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Get"
    },
    {
     "expr": "rate(post_requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Post"
    },
    {
     "expr": "rate(put_requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Put"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "creation_latency_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "active_users_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Authentication Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(success_auth_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(rate(failed_auth_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Pizza Purchases/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(pizzas_sold_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "Pizza Purchases"
    },
    {
     "expr": "sum(rate(creation_failures_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "Pizzas Failed"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(revenue_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "avg(creation_latency_ratio{source=\"jwt-pizza-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "memory_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  }
 ]
}